# Generated by Django 6.0.3 on 2026-03-28 13:56

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('adults_count', models.PositiveIntegerField(verbose_name='Adults')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='Children')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Contact Phone')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_client_secret', models.CharField(blank=True, max_length=500, null=True, verbose_name='Stripe Client Secret')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_tour_wishlist',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agency_submitted', 'Agency Submitted'), ('agency_approved', 'Agency Approved'), ('agency_rejected', 'Agency Rejected'), ('tour_submitted', 'Tour Submitted'), ('tour_approved', 'Tour Approved'), ('tour_rejected', 'Tour Rejected'), ('invitation_received', 'Invitation Received'), ('booking_confirmed', 'Booking Confirmed')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'tour')},
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
