# Generated by Django 6.0.3 on 2026-03-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_booking_remove_wishlist_unique_user_tour_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.hotelroom', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Room Count'),
        ),
    ]
