# Generated by Django 6.0.1 on 2026-01-31 21:42

import computedfields.resolver
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('HOTEL', 'Отель / Гостиница'), ('HOSTEL', 'Хостел'), ('FARM', 'Агроусадьба'), ('RESORT', 'Санаторий / Пансионат'), ('REC_CTR', 'База отдыха'), ('APART', 'Апартаменты / Квартира'), ('COTTAGE', 'Коттедж / Дом посуточно'), ('GLAMP', 'Глэмпинг / Кемпинг')], max_length=10, verbose_name='Тип объекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена до')),
                ('is_published', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('amenities', models.ManyToManyField(related_name='accommodations', to='accommodations.accommodationamenity', verbose_name='Удобства')),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='accommodations/images/', verbose_name='Фотография')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodation', verbose_name='Объект размещения')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
        migrations.CreateModel(
            name='AccommodationRating',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accommodations.accommodation', verbose_name='Объект размещения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка объекта',
                'verbose_name_plural': 'Оценки объектов',
                'constraints': [models.UniqueConstraint(fields=('user', 'accommodation'), name='unique_user_accommodation_rating')],
            },
        ),
    ]
